/** 旧世界仍在使用的商品、食材、资源和渔获。情绪收益由角色侧解释，不保存旧心情数值。 */
export type ItemDefinition = {
  id: string;
  description: string;
  categories: ("food" | "ingredient" | "valuable")[];
  source: "shop" | "supermarket" | "cafe" | "diner" | "park" | "coast" | "pond";
  price: number | null;
  salePrice: number | null;
  stamina: number;
  satiety: number;
  catchWeight: number;
};

export const items: ItemDefinition[] = [
  {
    id: "百奇",
    description: "涂层饼干棒，草莓口味。",
    categories: ["food"],
    source: "shop",
    price: 12,
    salePrice: null,
    stamina: 10,
    satiety: 5,
    catchWeight: 0,
  },
  {
    id: "纯软糖",
    description: "高果汁含量的软糖，芒果口味。",
    categories: ["food"],
    source: "shop",
    price: 12,
    salePrice: null,
    stamina: 10,
    satiety: 5,
    catchWeight: 0,
  },
  {
    id: "弹珠汽水糖",
    description: "汽水风味的硬糖，含气泡口感。",
    categories: ["food"],
    source: "shop",
    price: 8,
    salePrice: null,
    stamina: 10,
    satiety: 3,
    catchWeight: 0,
  },
  {
    id: "抹茶布丁",
    description: "带有抹茶的清香微苦，口感细腻。",
    categories: ["food"],
    source: "shop",
    price: 15,
    salePrice: null,
    stamina: 10,
    satiety: 5,
    catchWeight: 0,
  },
  {
    id: "波子汽水",
    description: "玻璃瓶装的清爽汽水，弹珠碰撞瓶口时会发出轻响。",
    categories: ["food"],
    source: "shop",
    price: 10,
    salePrice: null,
    stamina: 2,
    satiety: 2,
    catchWeight: 0,
  },
  {
    id: "铜锣烧",
    description: "松软的蜂蜜饼皮夹着红豆馅。",
    categories: ["food"],
    source: "shop",
    price: 12,
    salePrice: null,
    stamina: 10,
    satiety: 6,
    catchWeight: 0,
  },
  {
    id: "盐味仙贝",
    description: "烤得酥脆的盐味米饼。",
    categories: ["food"],
    source: "shop",
    price: 9,
    salePrice: null,
    stamina: 10,
    satiety: 4,
    catchWeight: 0,
  },
  {
    id: "草莓牛奶",
    description: "纸盒装草莓牛奶，甜味柔和。",
    categories: ["food"],
    source: "shop",
    price: 11,
    salePrice: null,
    stamina: 1,
    satiety: 3,
    catchWeight: 0,
  },
  {
    id: "红豆面包",
    description: "圆面包里填着绵密红豆馅。",
    categories: ["food"],
    source: "shop",
    price: 13,
    salePrice: null,
    stamina: 10,
    satiety: 6,
    catchWeight: 0,
  },
  {
    id: "蜂蜜柠檬糖",
    description: "蜂蜜柠檬味硬糖，酸甜清爽。",
    categories: ["food"],
    source: "shop",
    price: 8,
    salePrice: null,
    stamina: 1,
    satiety: 2,
    catchWeight: 0,
  },
  {
    id: "乌龙茶",
    description: "瓶装乌龙茶，茶香干净清淡。",
    categories: ["food"],
    source: "shop",
    price: 7,
    salePrice: null,
    stamina: 2,
    satiety: 1,
    catchWeight: 0,
  },
  {
    id: "白米",
    description: "家里常备的主食，多餐都能用上。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 3,
    satiety: 22,
    catchWeight: 0,
  },
  {
    id: "鸡蛋",
    description: "便宜又万能的蛋白质，适合早餐和简单料理。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 6,
    salePrice: null,
    stamina: 5,
    satiety: 12,
    catchWeight: 0,
  },
  {
    id: "豆腐",
    description: "清淡便宜的豆制品，可以做成温和的一餐。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 6,
    salePrice: null,
    stamina: 4,
    satiety: 14,
    catchWeight: 0,
  },
  {
    id: "卷心菜",
    description: "耐放的便宜蔬菜，适合搭配主食和肉类。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 2,
    satiety: 12,
    catchWeight: 0,
  },
  {
    id: "味噌",
    description: "可以用来做味噌汤，也能给简单饭菜增加风味。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 1,
    satiety: 8,
    catchWeight: 0,
  },
  {
    id: "速冻乌冬",
    description: "方便快速做一餐的冷冻乌冬。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 12,
    salePrice: null,
    stamina: 5,
    satiety: 28,
    catchWeight: 0,
  },
  {
    id: "鸡腿肉",
    description: "普通肉类食材，适合做一顿更扎实的家常饭。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 18,
    salePrice: null,
    stamina: 8,
    satiety: 18,
    catchWeight: 0,
  },
  {
    id: "鲑鱼切身",
    description: "稍微好一点的鱼类食材，适合认真做晚餐。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 24,
    salePrice: null,
    stamina: 7,
    satiety: 18,
    catchWeight: 0,
  },
  {
    id: "咖喱块",
    description: "咖喱调味块，可以让简单食材变成更有满足感的一餐。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 10,
    salePrice: null,
    stamina: 2,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "牛奶",
    description: "早餐、饮品或料理都能用到的牛奶。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 10,
    salePrice: null,
    stamina: 3,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "便当菜组合",
    description: "搭配好的便当菜组合，适合省心准备一餐。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 22,
    salePrice: null,
    stamina: 8,
    satiety: 34,
    catchWeight: 0,
  },
  {
    id: "西瓜",
    description: "清甜多汁的夏日水果，适合在炎热天气补充水分。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 18,
    salePrice: null,
    stamina: 3,
    satiety: 16,
    catchWeight: 0,
  },
  {
    id: "苹果",
    description: "方便携带的常见水果，适合作为日常点心。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 6,
    salePrice: null,
    stamina: 2,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "香蕉",
    description: "软糯方便的水果，适合快速补充一点体力。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 5,
    salePrice: null,
    stamina: 4,
    satiety: 12,
    catchWeight: 0,
  },
  {
    id: "草莓",
    description: "酸甜可口的时令水果，能让人心情变好。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 16,
    salePrice: null,
    stamina: 2,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "猪五花肉",
    description: "油脂丰富的猪肉，适合炒菜或炖煮一顿家常饭。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 20,
    salePrice: null,
    stamina: 9,
    satiety: 20,
    catchWeight: 0,
  },
  {
    id: "土豆",
    description: "耐放又有饱腹感的根茎食材，做法很多。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 6,
    salePrice: null,
    stamina: 3,
    satiety: 16,
    catchWeight: 0,
  },
  {
    id: "胡萝卜",
    description: "清甜的家常蔬菜，适合和肉类一起炖煮。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 6,
    salePrice: null,
    stamina: 2,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "洋葱",
    description: "炒香后能让家常料理更有风味的基础食材。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 6,
    salePrice: null,
    stamina: 2,
    satiety: 8,
    catchWeight: 0,
  },
  {
    id: "番茄",
    description: "酸甜多汁的蔬菜，适合做汤、炒蛋或凉拌。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 2,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "青椒",
    description: "带点清脆辣味的蔬菜，能给炒菜增添口感。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 2,
    satiety: 8,
    catchWeight: 0,
  },
  {
    id: "蘑菇",
    description: "鲜味十足的菌菇，适合搭配肉类和面食。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 10,
    salePrice: null,
    stamina: 3,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "面包",
    description: "方便快速解决一餐的主食，也能做成简单三明治。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 4,
    satiety: 20,
    catchWeight: 0,
  },
  {
    id: "奶酪",
    description: "浓郁的乳制品，能让料理更有满足感。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 14,
    salePrice: null,
    stamina: 4,
    satiety: 12,
    catchWeight: 0,
  },
  {
    id: "牛肉片",
    description: "适合快炒或火锅的牛肉片，能做出一顿扎实的料理。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 26,
    salePrice: null,
    stamina: 10,
    satiety: 20,
    catchWeight: 0,
  },
  {
    id: "猪肉末",
    description: "方便调味烹饪的猪肉末，适合做肉酱或家常炒菜。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 16,
    salePrice: null,
    stamina: 8,
    satiety: 18,
    catchWeight: 0,
  },
  {
    id: "培根",
    description: "咸香的培根，搭配早餐或炒菜都很方便。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 16,
    salePrice: null,
    stamina: 7,
    satiety: 16,
    catchWeight: 0,
  },
  {
    id: "虾",
    description: "鲜甜的虾，适合做成稍微讲究一点的料理。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 24,
    salePrice: null,
    stamina: 8,
    satiety: 16,
    catchWeight: 0,
  },
  {
    id: "鸡翅",
    description: "适合煎烤或炖煮的鸡翅，做出来很有满足感。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 18,
    salePrice: null,
    stamina: 8,
    satiety: 18,
    catchWeight: 0,
  },
  {
    id: "鹌鹑蛋",
    description: "小巧的鹌鹑蛋，适合加入便当或炖菜。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 4,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "西兰花",
    description: "清爽耐搭配的绿色蔬菜，适合快炒或焯水。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 10,
    salePrice: null,
    stamina: 3,
    satiety: 12,
    catchWeight: 0,
  },
  {
    id: "菠菜",
    description: "柔嫩的叶菜，适合做汤或简单清炒。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 2,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "玉米",
    description: "带有自然甜味的玉米，可以增加料理的饱腹感。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 3,
    satiety: 14,
    catchWeight: 0,
  },
  {
    id: "南瓜",
    description: "软糯香甜的南瓜，适合炖煮或做成浓汤。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 10,
    salePrice: null,
    stamina: 3,
    satiety: 16,
    catchWeight: 0,
  },
  {
    id: "茄子",
    description: "吸收酱汁后风味浓郁的茄子，适合家常烧制。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 8,
    salePrice: null,
    stamina: 2,
    satiety: 12,
    catchWeight: 0,
  },
  {
    id: "大葱",
    description: "常用的提香配菜，能让汤面和炒菜更有香气。",
    categories: ["ingredient"],
    source: "supermarket",
    price: 6,
    salePrice: null,
    stamina: 1,
    satiety: 6,
    catchWeight: 0,
  },
  {
    id: "深煎拼配",
    description: "深煎豆香扎实，苦韵干净，适合慢慢喝。",
    categories: ["food"],
    source: "cafe",
    price: 35,
    salePrice: null,
    stamina: 5,
    satiety: 8,
    catchWeight: 0,
  },
  {
    id: "浅煎拼配",
    description: "浅煎风味明亮，带一点果香，尾韵轻盈。",
    categories: ["food"],
    source: "cafe",
    price: 38,
    salePrice: null,
    stamina: 5,
    satiety: 8,
    catchWeight: 0,
  },
  {
    id: "冰滴咖啡",
    description: "低温慢萃，口感清透，冰凉里带着回甘。",
    categories: ["food"],
    source: "cafe",
    price: 42,
    salePrice: null,
    stamina: 5,
    satiety: 9,
    catchWeight: 0,
  },
  {
    id: "美式",
    description: "清爽直接，苦感利落，是最经典的一杯。",
    categories: ["food"],
    source: "cafe",
    price: 36,
    salePrice: null,
    stamina: 5,
    satiety: 9,
    catchWeight: 0,
  },
  {
    id: "牛奶咖啡",
    description: "热牛奶把咖啡的苦味收得柔和，温暖又顺口。",
    categories: ["food"],
    source: "cafe",
    price: 45,
    salePrice: null,
    stamina: 5,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "维也纳咖啡",
    description: "浓咖啡顶着柔软鲜奶油，入口香甜，余味还是咖啡香。",
    categories: ["food"],
    source: "cafe",
    price: 55,
    salePrice: null,
    stamina: 5,
    satiety: 11,
    catchWeight: 0,
  },
  {
    id: "乌冬面",
    description: "热乎乎的乌冬面，便宜、温和，适合轻松补一餐。",
    categories: ["food"],
    source: "diner",
    price: 18,
    salePrice: null,
    stamina: 6,
    satiety: 35,
    catchWeight: 0,
  },
  {
    id: "玉子烧定食",
    description: "玉子烧配米饭和味噌汤，简单但安心的定食。",
    categories: ["food"],
    source: "diner",
    price: 22,
    salePrice: null,
    stamina: 8,
    satiety: 38,
    catchWeight: 0,
  },
  {
    id: "咖喱饭",
    description: "浓郁的日式咖喱饭，能让饱腹感稳定恢复。",
    categories: ["food"],
    source: "diner",
    price: 26,
    salePrice: null,
    stamina: 10,
    satiety: 48,
    catchWeight: 0,
  },
  {
    id: "亲子丼",
    description: "鸡肉和鸡蛋盖在米饭上，热乎又有满足感。",
    categories: ["food"],
    source: "diner",
    price: 28,
    salePrice: null,
    stamina: 12,
    satiety: 50,
    catchWeight: 0,
  },
  {
    id: "唐扬鸡块定食",
    description: "唐扬鸡块配米饭和小菜，适合需要好好吃一顿的时候。",
    categories: ["food"],
    source: "diner",
    price: 32,
    salePrice: null,
    stamina: 12,
    satiety: 52,
    catchWeight: 0,
  },
  {
    id: "鲑鱼盐烤定食",
    description: "鲑鱼盐烤定食，清爽但认真，是稍微丰盛一点的日常饭。",
    categories: ["food"],
    source: "diner",
    price: 35,
    salePrice: null,
    stamina: 10,
    satiety: 50,
    catchWeight: 0,
  },
  {
    id: "今日定食",
    description: "当天推荐的完整定食，适合想省心吃饱的时候。",
    categories: ["food"],
    source: "diner",
    price: 35,
    salePrice: null,
    stamina: 12,
    satiety: 56,
    catchWeight: 0,
  },
  {
    id: "野莓",
    description: "长在灌木边的小浆果，酸甜清爽，一把就能吃掉。",
    categories: ["food", "ingredient"],
    source: "park",
    price: null,
    salePrice: 8,
    stamina: 3,
    satiety: 8,
    catchWeight: 0,
  },
  {
    id: "樱桃",
    description: "枝头熟透的樱桃，小小一把就很甜，适合边走边摘。",
    categories: ["food", "ingredient"],
    source: "park",
    price: null,
    salePrice: 12,
    stamina: 5,
    satiety: 12,
    catchWeight: 0,
  },
  {
    id: "小番茄",
    description: "圆滚滚的小番茄，带一点清甜汁水，也能拿回家做饭。",
    categories: ["food", "ingredient"],
    source: "park",
    price: null,
    salePrice: 20,
    stamina: 6,
    satiety: 16,
    catchWeight: 0,
  },
  {
    id: "黄瓜",
    description: "刚摘下来的黄瓜，脆生生的，带着一点清凉水气。",
    categories: ["food", "ingredient"],
    source: "park",
    price: null,
    salePrice: 10,
    stamina: 4,
    satiety: 10,
    catchWeight: 0,
  },
  {
    id: "花纹贝壳",
    description: "壳面有自然潮纹的贝壳，完整又好看，适合拿去售卖。",
    categories: ["valuable"],
    source: "coast",
    price: null,
    salePrice: 60,
    stamina: 0,
    satiety: 0,
    catchWeight: 0,
  },
  {
    id: "海玻璃",
    description: "被海浪打磨圆润的海玻璃，边缘柔和，颜色清透。",
    categories: ["valuable"],
    source: "coast",
    price: null,
    salePrice: 90,
    stamina: 0,
    satiety: 0,
    catchWeight: 0,
  },
  {
    id: "潮纹石",
    description: "被潮水磨出纹理的圆润石头，少见又耐看，能卖个好价钱。",
    categories: ["valuable"],
    source: "coast",
    price: null,
    salePrice: 180,
    stamina: 0,
    satiety: 0,
    catchWeight: 0,
  },
  {
    id: "旧玻璃瓶",
    description: "被海风和盐分磨旧的玻璃瓶，瓶身还算完整，带一点旧时光的味道。",
    categories: ["valuable"],
    source: "coast",
    price: null,
    salePrice: 70,
    stamina: 0,
    satiety: 0,
    catchWeight: 0,
  },
  {
    id: "海螺",
    description: "海螺壳纹清楚，里面的肉还能处理成食材，也能拿去卖掉。",
    categories: ["ingredient"],
    source: "coast",
    price: null,
    salePrice: 20,
    stamina: 6,
    satiety: 18,
    catchWeight: 0,
  },
  {
    id: "鲫鱼",
    description: "从水音池钓到的鲫鱼，个头不算大，适合带回家做饭。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 18,
    stamina: 5,
    satiety: 14,
    catchWeight: 20,
  },
  {
    id: "泥鳅",
    description: "从水音池钓到的泥鳅，滑溜溜的，也能处理成食材。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 16,
    stamina: 4,
    satiety: 12,
    catchWeight: 15,
  },
  {
    id: "鲤鱼",
    description: "从水音池钓到的鲤鱼，肉厚一些，认真收拾后可以做成一顿饭。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 40,
    stamina: 7,
    satiety: 18,
    catchWeight: 12,
  },
  {
    id: "河虾",
    description: "从水音池钓到的河虾，数量不算多，但收拾干净后也能下锅。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 22,
    stamina: 5,
    satiety: 13,
    catchWeight: 10,
  },
  {
    id: "鳑鲏",
    description: "从水音池钓到的鳑鲏，小小一尾，算是池边常见的渔获。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 14,
    stamina: 4,
    satiety: 10,
    catchWeight: 8,
  },
  {
    id: "麦穗鱼",
    description: "从水音池钓到的麦穗鱼，细小灵活，攒起来也能做成一道菜。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 15,
    stamina: 4,
    satiety: 11,
    catchWeight: 7,
  },
  {
    id: "鳊鱼",
    description: "从水音池钓到的鳊鱼，鱼身扁一些，算是今天运气不错的收获。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 52,
    stamina: 8,
    satiety: 20,
    catchWeight: 7,
  },
  {
    id: "鲶鱼",
    description: "从水音池钓到的鲶鱼，算是少见的大收获，可以卖个更好的价钱。",
    categories: ["ingredient"],
    source: "pond",
    price: null,
    salePrice: 78,
    stamina: 9,
    satiety: 22,
    catchWeight: 3,
  },
];

export const itemsById: ReadonlyMap<string, ItemDefinition> = new Map(
  items.map((item) => [item.id, item]),
);
