import {
  afternoon,
  daytime,
  minimumMoney,
  minimumStamina,
  weekdayMorning,
} from "../actions/conditions";
import type { PlaceDefinition, RouteDefinition } from "../map";

/** 小镇采用统一方位；内部布局只表达相对位置，通行仍以显式路线为准。 */
export const places: PlaceDefinition[] = [
  {
    id: "town",
    name: "小镇",
    description: "角色生活的小镇。",
    parentId: null,
    position: null,
    visibility: "public",
  },
  {
    id: "home",
    name: "家",
    description: "悠乃的家。",
    parentId: "town",
    position: { x: 420, y: -520 },
    visibility: "private",
  },
  {
    id: "school",
    name: "星见丘高校",
    description: "小镇北侧的学校。",
    parentId: "town",
    position: { x: 340, y: -190 },
    visibility: "public",
  },
  {
    id: "business_district",
    name: "商业区",
    description: "商店、食堂和车站所在的区域。",
    parentId: "town",
    position: { x: 690, y: -280 },
    visibility: "public",
  },
  {
    id: "park_area",
    name: "公园周边",
    description: "公园、池塘与神社所在的区域。",
    parentId: "town",
    position: { x: 480, y: -570 },
    visibility: "public",
  },
  {
    id: "coast_area",
    name: "海岸",
    description: "乘电车可以到达的海边。",
    parentId: "town",
    position: { x: 940, y: -690 },
    visibility: "public",
  },
  {
    id: "home_interior",
    name: "屋内",
    description: "家里的生活空间。",
    parentId: "home",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
  {
    id: "campus",
    name: "校园",
    description: "上课和学习的校园。",
    parentId: "school",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
  {
    id: "shop",
    name: "小町商店",
    description: "售卖零食和饮料的小商店。",
    parentId: "business_district",
    position: { x: 0, y: 1 },
    visibility: "public",
  },
  {
    id: "supermarket",
    name: "超市",
    description: "可以购买食材、出售物品。",
    parentId: "business_district",
    position: { x: 1, y: 1 },
    visibility: "public",
  },
  {
    id: "diner",
    name: "日和食堂",
    description: "提供热饭和定食的食堂。",
    parentId: "business_district",
    position: { x: 2, y: 1 },
    visibility: "public",
  },
  {
    id: "cafe",
    name: "薄暮咖啡",
    description: "可以喝咖啡、打工的咖啡店。",
    parentId: "business_district",
    position: { x: 3, y: 1 },
    visibility: "public",
  },
  {
    id: "station",
    name: "羽浦站",
    description: `商业区边缘的小车站，是前往月汐海岸的出发点。站台旁是一条沿陆地边缘蜿蜒的单线非电气化铁道，周围没有大城市车站的密集与喧闹，列车靠站时才会短暂聚起人声。
这里运行的是 KiHa 40 形单节编组列车，车身呈复古朱红色，外形方正厚重。车顶有空调外机与排气管，车头上方是一盏单孔探照大灯，窗框边缘留着金属氧化的痕迹。
车厢保留着老式下拉车窗、绒面对坐座椅、淡绿色木纹内壁和复古电风扇。列车运行时会有柴油机的轰鸣与车身的轻微震动。`,
    parentId: "business_district",
    position: { x: 1, y: 0 },
    visibility: "public",
  },
  {
    id: "park",
    name: "南风公园",
    description: "可以散步、采集果实和摆摊的公园。",
    parentId: "park_area",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
  {
    id: "pond",
    name: "水音池",
    description: "可以钓鱼的池塘。",
    parentId: "park_area",
    position: { x: 1, y: 0 },
    visibility: "public",
  },
  {
    id: "shrine",
    name: "结灯神社",
    description: `位于南风公园旁的小山上，沿缓坡和石阶可以到达。可以在这里参拜和许愿，本地人常在放学后或散步途中上来，也有人只是想安静地待一会儿。
境内不大，有木制拜殿、鸟居、手水舍和旧石灯。天气好时，从神社前的空地边缘可以俯瞰羽浦的住宅、小路、商业区屋顶和公园树影，远处还能望见海边方向的亮色。
这里与山下的日常生活仍很接近，有风时铃绪和树叶会轻轻作响，山下的生活声也隐约可闻，是小镇里适合整理心绪的地方。`,
    parentId: "park_area",
    position: { x: 2, y: 1 },
    visibility: "public",
  },
  {
    id: "coast",
    name: "月汐海岸",
    description: `可以散步、捡拾海边物品的海岸。沙滩绵延，近海有一座名为幻月岩的孤立礁石，几株古松扎根其上；隔着幽蓝海湾，可以远望连绵的圣山。
圣山并非全年覆雪：11 月至次年 3 月，群山会披上积雪；其他时节以青灰色山脊与海面相映，山峰有时隐在云雾中。冬季晴朗清晨，山头可能被阳光染成金粉色，雪山与海浪相映是这里有名的景色。
沿潮线散步时，有机会找到星砂贝壳、海玻璃，偶尔还能遇到月汐珍珠；实际能捡到什么取决于当时的现场资源。`,
    parentId: "coast_area",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
];

/** 逐条迁移旧有向路线，保留往返差异。 */
export const routes: RouteDefinition[] = [
  {
    id: "home_to_campus",
    fromPlaceId: "home_interior",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 20,
    cost: { money: 0, stamina: 7, satiety: 5 },
    conditions: [weekdayMorning],
  },
  {
    id: "home_to_shop",
    fromPlaceId: "home_interior",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_cafe",
    fromPlaceId: "home_interior",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_supermarket",
    fromPlaceId: "home_interior",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_diner",
    fromPlaceId: "home_interior",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_park",
    fromPlaceId: "home_interior",
    toPlaceId: "park",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(3)],
  },
  {
    id: "home_to_shrine",
    fromPlaceId: "home_interior",
    toPlaceId: "shrine",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(3)],
  },
  {
    id: "campus_to_home",
    fromPlaceId: "campus",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 20,
    cost: { money: 0, stamina: 7, satiety: 5 },
    conditions: [afternoon, minimumStamina(10)],
  },
  {
    id: "campus_to_shop",
    fromPlaceId: "campus",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "campus_to_cafe",
    fromPlaceId: "campus",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "campus_to_supermarket",
    fromPlaceId: "campus",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "campus_to_diner",
    fromPlaceId: "campus",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "cafe_to_home",
    fromPlaceId: "cafe",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "cafe_to_campus",
    fromPlaceId: "cafe",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "cafe_to_diner",
    fromPlaceId: "cafe",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "cafe_to_station",
    fromPlaceId: "cafe",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "diner_to_home",
    fromPlaceId: "diner",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "diner_to_campus",
    fromPlaceId: "diner",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "diner_to_supermarket",
    fromPlaceId: "diner",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "diner_to_cafe",
    fromPlaceId: "diner",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "diner_to_station",
    fromPlaceId: "diner",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "shop_to_home",
    fromPlaceId: "shop",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "shop_to_campus",
    fromPlaceId: "shop",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "shop_to_supermarket",
    fromPlaceId: "shop",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "shop_to_station",
    fromPlaceId: "shop",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "supermarket_to_home",
    fromPlaceId: "supermarket",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "supermarket_to_campus",
    fromPlaceId: "supermarket",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "supermarket_to_shop",
    fromPlaceId: "supermarket",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "supermarket_to_diner",
    fromPlaceId: "supermarket",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "supermarket_to_station",
    fromPlaceId: "supermarket",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_shop",
    fromPlaceId: "station",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_supermarket",
    fromPlaceId: "station",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_diner",
    fromPlaceId: "station",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_cafe",
    fromPlaceId: "station",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_coast",
    fromPlaceId: "station",
    toPlaceId: "coast",
    kind: "path",
    mode: "train",
    durationMinutes: 15,
    cost: { money: 3, stamina: 7, satiety: 5 },
    conditions: [minimumMoney(6)],
  },
  {
    id: "park_to_home",
    fromPlaceId: "park",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "park_to_shrine",
    fromPlaceId: "park",
    toPlaceId: "shrine",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime],
  },
  {
    id: "park_to_pond",
    fromPlaceId: "park",
    toPlaceId: "pond",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "pond_to_park",
    fromPlaceId: "pond",
    toPlaceId: "park",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "shrine_to_park",
    fromPlaceId: "shrine",
    toPlaceId: "park",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "shrine_to_home",
    fromPlaceId: "shrine",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "coast_to_station",
    fromPlaceId: "coast",
    toPlaceId: "station",
    kind: "path",
    mode: "train",
    durationMinutes: 15,
    cost: { money: 3, stamina: 7, satiety: 5 },
    conditions: [minimumMoney(3)],
  },
];
