import {
  afternoon,
  daytime,
  minimumMoney,
  minimumStamina,
  weekdayMorning,
} from "../actions/conditions";
import type { PlaceDefinition, RouteDefinition } from "../map";

/** 小镇采用统一方位；内部布局只表达相对位置，通行仍以显式路线为准。 */
export const places: PlaceDefinition[] = [
  {
    id: "town",
    name: "小镇",
    description: "角色生活的小镇。",
    parentId: null,
    position: null,
    visibility: "public",
  },
  {
    id: "home",
    name: "家",
    description: "悠乃的家。",
    parentId: "town",
    position: { x: 420, y: -520 },
    visibility: "private",
  },
  {
    id: "school",
    name: "星见丘高校",
    description: "小镇北侧的学校。",
    parentId: "town",
    position: { x: 340, y: -190 },
    visibility: "public",
  },
  {
    id: "business_district",
    name: "商业区",
    description: "商店、食堂和车站所在的区域。",
    parentId: "town",
    position: { x: 690, y: -280 },
    visibility: "public",
  },
  {
    id: "park_area",
    name: "公园周边",
    description: "公园、池塘与神社所在的区域。",
    parentId: "town",
    position: { x: 480, y: -570 },
    visibility: "public",
  },
  {
    id: "coast_area",
    name: "海岸",
    description: "乘电车可以到达的海边。",
    parentId: "town",
    position: { x: 940, y: -690 },
    visibility: "public",
  },
  {
    id: "home_interior",
    name: "屋内",
    description: "家里的生活空间。",
    parentId: "home",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
  {
    id: "campus",
    name: "校园",
    description: "上课和学习的校园。",
    parentId: "school",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
  {
    id: "shop",
    name: "小町商店",
    description: "售卖零食和饮料的小商店。",
    parentId: "business_district",
    position: { x: 0, y: 1 },
    visibility: "public",
  },
  {
    id: "supermarket",
    name: "超市",
    description: "可以购买食材、出售物品。",
    parentId: "business_district",
    position: { x: 1, y: 1 },
    visibility: "public",
  },
  {
    id: "diner",
    name: "日和食堂",
    description: "提供热饭和定食的食堂。",
    parentId: "business_district",
    position: { x: 2, y: 1 },
    visibility: "public",
  },
  {
    id: "cafe",
    name: "薄暮咖啡",
    description: "可以喝咖啡、打工的咖啡店。",
    parentId: "business_district",
    position: { x: 3, y: 1 },
    visibility: "public",
  },
  {
    id: "station",
    name: "羽浦站",
    description: "通往海岸的电车站。",
    parentId: "business_district",
    position: { x: 1, y: 0 },
    visibility: "public",
  },
  {
    id: "park",
    name: "南风公园",
    description: "可以散步、采集果实和摆摊的公园。",
    parentId: "park_area",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
  {
    id: "pond",
    name: "水音池",
    description: "可以钓鱼的池塘。",
    parentId: "park_area",
    position: { x: 1, y: 0 },
    visibility: "public",
  },
  {
    id: "shrine",
    name: "结灯神社",
    description: "可以参拜和许愿的神社。",
    parentId: "park_area",
    position: { x: 2, y: 1 },
    visibility: "public",
  },
  {
    id: "coast",
    name: "月汐海岸",
    description: "可以散步、捡拾海边物品的海岸。",
    parentId: "coast_area",
    position: { x: 0, y: 0 },
    visibility: "public",
  },
];

/** 逐条迁移旧有向路线，保留往返差异。 */
export const routes: RouteDefinition[] = [
  {
    id: "home_to_campus",
    fromPlaceId: "home_interior",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 20,
    cost: { money: 0, stamina: 7, satiety: 5 },
    conditions: [weekdayMorning],
  },
  {
    id: "home_to_shop",
    fromPlaceId: "home_interior",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_cafe",
    fromPlaceId: "home_interior",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_supermarket",
    fromPlaceId: "home_interior",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_diner",
    fromPlaceId: "home_interior",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "home_to_park",
    fromPlaceId: "home_interior",
    toPlaceId: "park",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(3)],
  },
  {
    id: "home_to_shrine",
    fromPlaceId: "home_interior",
    toPlaceId: "shrine",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(3)],
  },
  {
    id: "campus_to_home",
    fromPlaceId: "campus",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 20,
    cost: { money: 0, stamina: 7, satiety: 5 },
    conditions: [afternoon, minimumStamina(10)],
  },
  {
    id: "campus_to_shop",
    fromPlaceId: "campus",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "campus_to_cafe",
    fromPlaceId: "campus",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "campus_to_supermarket",
    fromPlaceId: "campus",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "campus_to_diner",
    fromPlaceId: "campus",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime, minimumStamina(5)],
  },
  {
    id: "cafe_to_home",
    fromPlaceId: "cafe",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "cafe_to_campus",
    fromPlaceId: "cafe",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "cafe_to_diner",
    fromPlaceId: "cafe",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "cafe_to_station",
    fromPlaceId: "cafe",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "diner_to_home",
    fromPlaceId: "diner",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "diner_to_campus",
    fromPlaceId: "diner",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "diner_to_supermarket",
    fromPlaceId: "diner",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "diner_to_cafe",
    fromPlaceId: "diner",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "diner_to_station",
    fromPlaceId: "diner",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "shop_to_home",
    fromPlaceId: "shop",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "shop_to_campus",
    fromPlaceId: "shop",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "shop_to_supermarket",
    fromPlaceId: "shop",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "shop_to_station",
    fromPlaceId: "shop",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "supermarket_to_home",
    fromPlaceId: "supermarket",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 5, satiety: 3 },
    conditions: [],
  },
  {
    id: "supermarket_to_campus",
    fromPlaceId: "supermarket",
    toPlaceId: "campus",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "supermarket_to_shop",
    fromPlaceId: "supermarket",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "supermarket_to_diner",
    fromPlaceId: "supermarket",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "supermarket_to_station",
    fromPlaceId: "supermarket",
    toPlaceId: "station",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_shop",
    fromPlaceId: "station",
    toPlaceId: "shop",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_supermarket",
    fromPlaceId: "station",
    toPlaceId: "supermarket",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_diner",
    fromPlaceId: "station",
    toPlaceId: "diner",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_cafe",
    fromPlaceId: "station",
    toPlaceId: "cafe",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 1, satiety: 1 },
    conditions: [],
  },
  {
    id: "station_to_coast",
    fromPlaceId: "station",
    toPlaceId: "coast",
    kind: "path",
    mode: "train",
    durationMinutes: 15,
    cost: { money: 3, stamina: 7, satiety: 5 },
    conditions: [minimumMoney(6)],
  },
  {
    id: "park_to_home",
    fromPlaceId: "park",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "park_to_shrine",
    fromPlaceId: "park",
    toPlaceId: "shrine",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [daytime],
  },
  {
    id: "park_to_pond",
    fromPlaceId: "park",
    toPlaceId: "pond",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "pond_to_park",
    fromPlaceId: "pond",
    toPlaceId: "park",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "shrine_to_park",
    fromPlaceId: "shrine",
    toPlaceId: "park",
    kind: "path",
    mode: "walk",
    durationMinutes: 5,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "shrine_to_home",
    fromPlaceId: "shrine",
    toPlaceId: "home_interior",
    kind: "path",
    mode: "walk",
    durationMinutes: 10,
    cost: { money: 0, stamina: 3, satiety: 2 },
    conditions: [],
  },
  {
    id: "coast_to_station",
    fromPlaceId: "coast",
    toPlaceId: "station",
    kind: "path",
    mode: "train",
    durationMinutes: 15,
    cost: { money: 3, stamina: 7, satiety: 5 },
    conditions: [minimumMoney(3)],
  },
];
